CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_DISPLAY=y

# undergnlow brighness 50%
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10

CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
